# Generated by Django 6.1 on 2026-08-11 05:55

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a whole-family goal; set a member for a personal goal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.member'),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='term',
            field=models.CharField(choices=[('short', 'Short term'), ('medium', 'Medium term'), ('long', 'Long term')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='join_code',
            field=models.CharField(default=core.models.generate_join_code, max_length=6),
        ),
        migrations.AddField(
            model_name='member',
            name='requested_role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('earner', 'Earner'), ('contributor', 'Contributor'), ('dependant', 'Dependant')], default='earner', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_months',
            field=models.IntegerField(default=12),
        ),
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tier', models.CharField(choices=[('income', 'Income'), ('essential', 'Essential'), ('committed', 'Committed'), ('discretionary', 'Discretionary')], max_length=20)),
                ('day_of_month', models.IntegerField(help_text='Day (1-28) this repeats each month')),
                ('active', models.BooleanField(default=True)),
                ('last_run', models.DateField(blank=True, help_text='Last date this rule posted a transaction', null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to='core.household')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to='core.member')),
            ],
        ),
    ]
