# Generated by Django 6.1 on 2026-08-11 05:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_goal_owner_goal_target_date_goal_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='join_code',
            field=models.CharField(default=core.models.generate_join_code, max_length=6, unique=True),
        ),
    ]
